# Generated by Django 5.2.4 on 2025-10-14 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cropcycle', '0001_initial'),
        ('inventory', '0004_company_name_mr_product_name_mr_and_more'),
        ('recommandations', '0001_initial'),
        ('schedule', '0005_remove_cropspecificbenefit_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropvariety',
            name='crop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='recommandations.crop'),
        ),
        migrations.AddField(
            model_name='farmercropcycle',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropcycle.cropvariety'),
        ),
        migrations.AddField(
            model_name='farmercropcycle',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='schedule.farmer'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='cropcycle.cropvariety'),
        ),
        migrations.AddField(
            model_name='farmercropcycle',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cycles', to='cropcycle.schedule'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='cropcycle.schedule'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cropcycle.scheduletask'),
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='products',
            field=models.ManyToManyField(related_name='schedule_tasks', through='cropcycle.TaskProduct', to='inventory.product'),
        ),
        migrations.AlterUniqueTogether(
            name='cropvariety',
            unique_together={('crop', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='taskproduct',
            unique_together={('task', 'product')},
        ),
    ]
