# Generated by Django 5.2.4 on 2025-10-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cropcycle', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskproduct',
            name='dosage_area_unit',
            field=models.CharField(choices=[('ACRE', 'Per Acre'), ('HECTARE', 'Per Hectare')], default='ACRE', max_length=20),
        ),
        migrations.AddField(
            model_name='taskproduct',
            name='dosage_per_area',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Area unit this dosage is for (e.g., 1 acre, 1 hectare)', max_digits=10),
        ),
    ]
