# Generated by Django 5.2.4 on 2025-10-24 07:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('product_type', models.CharField(blank=True, max_length=100, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_marathi', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='analytics.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Varieties',
                'ordering': ['crop', 'name'],
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DayRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_from', models.CharField(choices=[('plantation', 'Plantation'), ('pruning', 'Pruning')], max_length=20)),
                ('start_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_day', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('info', models.TextField(help_text='Information about what to do in this activity')),
                ('info_marathi', models.TextField(blank=True, help_text='Information in Marathi', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_ranges', to='analytics.activity')),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_ranges', to='analytics.cropvariety')),
            ],
            options={
                'verbose_name_plural': 'Day Ranges',
                'ordering': ['crop_variety', 'start_day'],
            },
        ),
        migrations.CreateModel(
            name='DayRangeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('dosage_unit', models.CharField(choices=[('gm/acre', 'Gram per Acre'), ('kg/acre', 'Kilogram per Acre'), ('ml/acre', 'Milliliter per Acre'), ('liter/acre', 'Liter per Acre'), ('gm/liter', 'Gram per Liter'), ('ml/liter', 'Milliliter per Liter'), ('gm/plant', 'Gram per Plant'), ('ml/plant', 'Milliliter per Plant')], max_length=20)),
                ('application_method', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_range', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='analytics.dayrange')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_range_products', to='analytics.product')),
            ],
            options={
                'verbose_name_plural': 'Day Range Products',
                'ordering': ['day_range', 'product'],
            },
        ),
    ]
