# Generated by Django 5.2.4 on 2025-10-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farmer',
        ),
    ]
