# Generated by Django 5.2.4 on 2025-10-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_delete_farmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='benefits',
        ),
    ]
