# Generated by Django 5.2.4 on 2025-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name_mr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_mr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='technical_composition_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Technical Composition (Marathi)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='description_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Marathi)'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='name_mr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (Marathi)'),
        ),
    ]
