# Generated by Django 5.2.4 on 2025-10-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_productsku_options_company_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='benefits',
            field=models.TextField(blank=True, help_text='Key benefits and expected impact', null=True, verbose_name='Benefits/Impact'),
        ),
        migrations.AddField(
            model_name='product',
            name='benefits_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Benefits (Marathi)'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose',
            field=models.TextField(blank=True, help_text='What is this product used for?', null=True, verbose_name='Purpose/Use Cases'),
        ),
        migrations.AddField(
            model_name='product',
            name='purpose_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Purpose (Marathi)'),
        ),
        migrations.AddField(
            model_name='productsku',
            name='image_path',
            field=models.CharField(blank=True, help_text='Path to static image file (e.g., products/fertilizer-10kg.jpg)', max_length=500, null=True),
        ),
    ]
