# Generated by Django 5.2.4 on 2025-10-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_benefits_product_benefits_mr_product_purpose_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsku',
            name='image_path',
        ),
        migrations.AddField(
            model_name='productsku',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/skus/'),
        ),
    ]
