# Generated by Django 5.2.4 on 2025-10-13 10:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('crops', models.ManyToManyField(blank=True, related_name='advisories', to='schedule.crop')),
            ],
            options={
                'verbose_name_plural': 'Advisories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropVariety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='schedule.crop')),
            ],
            options={
                'verbose_name_plural': 'Crop Varieties',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('crop', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(max_length=100)),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.cropvariety')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarmerCropCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sowing_date', models.DateField()),
                ('crop_variety', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_cycles', to='schedule.cropvariety')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_cycles', to='schedule.farmer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='farmer_cycles', to='schedule.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(max_length=255)),
                ('start_day', models.IntegerField(help_text='Days after sowing to start this task')),
                ('end_day', models.IntegerField(help_text='Days after sowing to end this task')),
                ('application_type', models.CharField(max_length=100)),
                ('purpose_and_benefits', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='schedule.schedule')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dosage_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dosage_unit', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.scheduletask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('task', 'product')},
            },
        ),
        migrations.AddField(
            model_name='scheduletask',
            name='products',
            field=models.ManyToManyField(related_name='schedule_tasks', through='schedule.TaskProduct', to='inventory.product'),
        ),
        migrations.CreateModel(
            name='FarmerTaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('farmer_crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='schedule.farmercropcycle')),
                ('schedule_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_tasks', to='schedule.scheduletask')),
            ],
            options={
                'verbose_name_plural': 'Farmer Task Statuses',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('farmer_crop_cycle', 'schedule_task')},
            },
        ),
    ]
