# Generated by Django 5.2.4 on 2025-10-13 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_benefits'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletask',
            name='end_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scheduletask',
            name='start_day',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='CropSpecificBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Describe the benefit of using this product on this specific crop.')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_benefits', to='schedule.crop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_benefits', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Crop Specific Benefits',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('product', 'crop')},
            },
        ),
    ]
