# Generated by Django 5.2.4 on 2025-10-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_scheduletask_end_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='description_mr',
            field=models.TextField(blank=True, help_text='Benefit description in Marathi', null=True),
        ),
    ]
