# Generated by Django 5.2.4 on 2025-10-14 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_cropspecificbenefit_description_mr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmercropcycle',
            options={'ordering': ['-sowing_date']},
        ),
        migrations.AlterModelOptions(
            name='farmertaskstatus',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='farmertaskstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='farmercropcycle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='farmertaskstatus',
            name='delay_date',
            field=models.DateField(blank=True, help_text='Date when delay was recorded', null=True),
        ),
        migrations.AddField(
            model_name='farmertaskstatus',
            name='delay_days',
            field=models.IntegerField(default=0, help_text='Number of days delayed'),
        ),
        migrations.AddField(
            model_name='farmertaskstatus',
            name='delay_reason',
            field=models.TextField(blank=True, help_text='Reason for delay', null=True),
        ),
        migrations.AlterField(
            model_name='farmercropcycle',
            name='crop_variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.cropvariety'),
        ),
        migrations.AlterField(
            model_name='farmercropcycle',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_cycles', to='schedule.schedule'),
        ),
    ]
