# Generated by Django 5.2.4 on 2025-10-14 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_farmercropcycle_options_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='cropspecificbenefit',
        #     name='crop',
        # ),
        # migrations.RemoveField(
        #     model_name='cropvariety',
        #     name='crop',
        # ),
        migrations.AlterUniqueTogether(
            name='cropspecificbenefit',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cropspecificbenefit',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='cropvariety',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='crop_variety',
        ),
        migrations.RemoveField(
            model_name='farmercropcycle',
            name='crop_variety',
        ),
        migrations.RemoveField(
            model_name='farmercropcycle',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmercropcycle',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='farmertaskstatus',
            name='farmer_crop_cycle',
        ),
        migrations.RemoveField(
            model_name='farmertaskstatus',
            name='schedule_task',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='scheduletask',
            name='products',
        ),
        # migrations.RemoveField(
        #     model_name='taskproduct',
        #     name='task',
        # ),
        migrations.AlterUniqueTogether(
            name='taskproduct',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='taskproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='Advisory',
        ),
        migrations.DeleteModel(
            name='Crop',
        ),
        migrations.DeleteModel(
            name='CropSpecificBenefit',
        ),
        migrations.DeleteModel(
            name='CropVariety',
        ),
        migrations.DeleteModel(
            name='FarmerCropCycle',
        ),
        migrations.DeleteModel(
            name='FarmerTaskStatus',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='ScheduleTask',
        ),
        migrations.DeleteModel(
            name='TaskProduct',
        ),
    ]
