# Generated by Django 5.2.4 on 2025-10-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_remove_cropspecificbenefit_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='farm_size',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Farm size in acres', max_digits=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='farm_size_unit',
            field=models.CharField(choices=[('ACRE', 'Acre'), ('HECTARE', 'Hectare')], default='ACRE', max_length=20),
        ),
    ]
