# Generated by Django 5.2.4 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_interactive_response_received',
            field=models.BooleanField(default=False, help_text='True if a reply to this interactive message has been processed'),
        ),
    ]
