# Generated by Django 5.2.4 on 2025-09-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, help_text='e.g., sent, delivered, read', max_length=50, null=True),
        ),
    ]
