# Generated by Django 5.2.4 on 2025-09-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_message_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_node_id',
            field=models.CharField(blank=True, help_text='The ID of the flow node that sent this message.', max_length=255, null=True),
        ),
    ]
