# Generated by Django 5.2.4 on 2025-09-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_message_is_interactive_response_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(blank=True, help_text='e.g., sent, delivered, read', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
