# Generated by Django 5.2.4 on 2025-09-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_message_source_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A unique name for the form.', max_length=100, unique=True)),
                ('structure', models.JSONField(help_text='The JSON structure of the form fields.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
