# Generated by Django 5.2.4 on 2025-09-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_message_delivery_status_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery',
            field=models.CharField(blank=True, help_text='e.g., sent, delivered, read', max_length=50, null=True),
        ),
    ]
