# Generated by Django 5.2.4 on 2025-10-03 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_whatsappform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('farm_size_acres', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('seeding_date', models.DateField()),
                ('germination_date', models.DateField()),
                ('vegetative_stage_start', models.DateField()),
                ('flowering_stage_start', models.DateField()),
                ('fruiting_stage_start', models.DateField()),
                ('harvesting_date', models.DateField()),
                ('next_crop_recommendation', models.CharField(blank=True, max_length=255)),
                ('soil_improvement_tip', models.TextField(blank=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_details', to='registration.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention_type', models.CharField(choices=[('Fertilizer', 'Fertilizer'), ('Pesticide', 'Pesticide'), ('Pruning/Weeding', 'Pruning/Weeding'), ('Other', 'Other')], max_length=50)),
                ('date', models.DateField()),
                ('product_used', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('crop_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='registration.cropdetails')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
