# Generated by Django 5.2.4 on 2025-08-25 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0029_helprequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredLabourer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=15)),
                ('mukkadam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_labourers', to='registration.mukkadam')),
            ],
            options={
                'unique_together': {('mukkadam', 'name')},
            },
        ),
    ]
