# Generated by Django 5.2.4 on 2025-08-29 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_whatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="The user's WhatsApp ID (their phone number).", max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text="The user's WhatsApp profile name.", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_contact_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(help_text='The unique WhatsApp Message ID from Meta.', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('reaction', 'Reaction'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('text_content', models.TextField(blank=True, help_text='Content for text messages or emoji reactions.', null=True)),
                ('media_id', models.CharField(blank=True, help_text="Meta's ID for the uploaded media.", max_length=255, null=True)),
                ('media_url', models.URLField(blank=True, help_text='Public URL for the media file.', max_length=1024, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp from the WhatsApp message.')),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], help_text='Status for outbound messages.', max_length=20, null=True)),
                ('raw_data', models.JSONField(help_text='The raw, complete webhook payload from Meta for debugging.')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='registration.chatcontact')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
