# Generated by Django 5.2.4 on 2025-08-30 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0032_chatcontact_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media_id',
        ),
        migrations.RemoveField(
            model_name='message',
            name='media_url',
        ),
        migrations.AddField(
            model_name='message',
            name='caption',
            field=models.TextField(blank=True, help_text='Caption for media messages.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, help_text='Locally saved media file.', null=True, upload_to='whatsapp_media/'),
        ),
        migrations.AddField(
            model_name='message',
            name='replied_to',
            field=models.ForeignKey(blank=True, help_text='The message this message is a reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='registration.message'),
        ),
        migrations.AlterField(
            model_name='chatcontact',
            name='last_contact_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('contact', 'Contact'), ('reaction', 'Reaction'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text_content',
            field=models.TextField(blank=True, help_text='Content for text messages or placeholders for media.', null=True),
        ),
    ]
