# Generated by Django 5.2.4 on 2025-08-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_remove_message_media_id_remove_message_media_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='raw_data',
            field=models.JSONField(blank=True, help_text='The raw, complete webhook payload from Meta for debugging.', null=True),
        ),
    ]
