# Generated by Django 5.2.4 on 2025-08-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_alter_message_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
