# Generated by Django 5.2.4 on 2025-08-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_message_media_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
