# Generated by Django 5.2.4 on 2025-08-31 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0036_message_contact_name_message_contact_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_view_once',
            field=models.BooleanField(default=False, help_text='True if this message is a one-time view media.'),
        ),
        migrations.AddField(
            model_name='message',
            name='reaction',
            field=models.CharField(blank=True, help_text='Reaction emoji (e.g. 👍, ❤️).', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_file',
            field=models.FileField(blank=True, help_text='Locally saved media file.', max_length=500, null=True, upload_to='whatsapp_media/'),
        ),
    ]
