# Generated by Django 5.2.4 on 2025-09-08 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0037_message_is_view_once_message_reaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='The exact name of the WhatsApp template this flow is for.', max_length=255, unique=True)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFlowSession',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.flow')),
            ],
        ),
    ]
