# Generated by Django 5.2.4 on 2025-09-09 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0038_flow_userflowsession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflowsession',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='userflowsession',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Flow',
        ),
        migrations.DeleteModel(
            name='UserFlowSession',
        ),
    ]
