# Generated by Django 5.2.4 on 2025-10-14 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cropcycle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerTaskStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_start_date', models.DateField()),
                ('planned_end_date', models.DateField()),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('delay_days', models.IntegerField(default=0, help_text='Number of days delayed')),
                ('delay_reason', models.TextField(blank=True, help_text='Reason for delay', null=True)),
                ('delay_date', models.DateField(blank=True, help_text='Date when delay was recorded', null=True)),
                ('farmer_crop_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_statuses', to='cropcycle.farmercropcycle')),
                ('schedule_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_tasks', to='cropcycle.scheduletask')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
