# Generated by Django 5.2.4 on 2025-10-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmertaskstatus',
            options={'ordering': ['farmer_crop_cycle', 'schedule_task__start_day'], 'verbose_name': 'Farmer Task Status', 'verbose_name_plural': 'Farmer Task Statuses'},
        ),
        migrations.AlterField(
            model_name='farmertaskstatus',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20),
        ),
    ]
