# Generated by Django 5.2.4 on 2025-10-14 06:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0004_company_name_mr_product_name_mr_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('crops', models.ManyToManyField(blank=True, related_name='advisories', to='recommandations.crop')),
            ],
            options={
                'verbose_name_plural': 'Advisories',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CropSpecificBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Describe the benefit of using this product on this specific crop.')),
                ('description_mr', models.TextField(blank=True, help_text='Benefit description in Marathi', null=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_benefits', to='recommandations.crop')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_benefits', to='inventory.product')),
            ],
            options={
                'verbose_name_plural': 'Crop Specific Benefits',
                'ordering': ['-created_at'],
                'abstract': False,
                'unique_together': {('product', 'crop')},
            },
        ),
    ]
