# Generated by Django 5.2.4 on 2025-10-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommandations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['-created_at'], 'verbose_name': 'Crop', 'verbose_name_plural': 'Crops'},
        ),
        migrations.AlterModelOptions(
            name='cropspecificbenefit',
            options={'ordering': ['-priority', 'crop__name'], 'verbose_name': 'Crop-Specific Benefit', 'verbose_name_plural': 'Crop-Specific Benefits'},
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crop',
            name='name_mr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='application_timing',
            field=models.CharField(blank=True, help_text='When to apply (e.g., "30 days after planting")', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='application_timing_mr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Timing (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='dosage_recommendation',
            field=models.CharField(blank=True, help_text='Recommended dosage per acre', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='dosage_recommendation_mr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dosage (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='expected_results',
            field=models.TextField(blank=True, null=True, verbose_name='Expected Results'),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='expected_results_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Results (Marathi)'),
        ),
        migrations.AddField(
            model_name='cropspecificbenefit',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority appears first'),
        ),
        migrations.AlterField(
            model_name='cropspecificbenefit',
            name='description',
            field=models.TextField(verbose_name='Benefit Description'),
        ),
        migrations.AlterField(
            model_name='cropspecificbenefit',
            name='description_mr',
            field=models.TextField(blank=True, null=True, verbose_name='Description (Marathi)'),
        ),
    ]
