# Generated by Django 5.2.4 on 2025-10-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Flow', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the flow is currently active and can be triggered.')),
                ('template_name', models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=250)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Flows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Flowss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=250)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
