# Generated by Django 5.2.4 on 2025-10-24 04:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="The user's WhatsApp ID (their phone number).", max_length=50, unique=True)),
                ('name', models.CharField(blank=True, help_text="The user's WhatsApp profile name.", max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_contact_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled Flow', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the flow is currently active and can be triggered.')),
                ('template_name', models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=250)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Flows',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Flowss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=250)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppFlowForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta_flow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_category', models.CharField(default='UTILITY', max_length=50)),
                ('template_body', models.TextField()),
                ('template_button_text', models.CharField(default='Open Form', max_length=20)),
                ('screens_data', models.JSONField()),
                ('flow_status', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Flow Form',
                'verbose_name_plural': 'WhatsApp Flow Forms',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wamid', models.CharField(help_text='The unique WhatsApp Message ID from Meta.', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document'), ('sticker', 'Sticker'), ('contact', 'Contact'), ('reaction', 'Reaction'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('is_view_once', models.BooleanField(default=False, help_text='True if this message is a one-time view media.')),
                ('text_content', models.TextField(blank=True, help_text='Content for text messages or placeholders for media.', null=True)),
                ('caption', models.TextField(blank=True, help_text='Caption for media messages.', null=True)),
                ('media_file', models.FileField(blank=True, help_text='Locally saved media file.', max_length=500, null=True, upload_to='whatsapp_media/')),
                ('reaction', models.CharField(blank=True, help_text='Reaction emoji (e.g. 👍, ❤️).', max_length=50, null=True)),
                ('delivery_status', models.CharField(blank=True, help_text='e.g., sent, delivered, read', max_length=50, null=True)),
                ('source_node_id', models.CharField(blank=True, help_text='The ID of the flow node that sent this message.', max_length=255, null=True)),
                ('timestamp', models.DateTimeField(help_text='Timestamp from the WhatsApp message.')),
                ('media_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], max_length=50, null=True)),
                ('contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('raw_data', models.JSONField(blank=True, help_text='The raw, complete webhook payload from Meta for debugging.', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='flow.chatcontact')),
                ('replied_to', models.ForeignKey(blank=True, help_text='The message this message is a reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='flow.message')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, help_text='The unique ID from Meta for this call', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(default='initiated', help_text='e.g., ringing, answered, ended, missed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when the call was ended or missed', null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='flow.chatcontact')),
            ],
        ),
        migrations.CreateModel(
            name='UserFlowSessions',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flow.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_waiting_for_location', models.BooleanField(default=False)),
                ('waiting_for_flow_completion', models.BooleanField(default=False)),
                ('flow_form_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flows')),
                ('latitude_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latitude_sessions', to='flow.attribute')),
                ('longitude_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longitude_sessions', to='flow.attribute')),
                ('waiting_for_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.attribute')),
                ('waiting_for_image_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sessions', to='flow.attribute')),
            ],
            options={
                'verbose_name_plural': 'User Flow Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserFlowSessionss',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='flow.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flowss')),
            ],
        ),
        migrations.CreateModel(
            name='ContactAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_values', to='flow.attribute')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='flow.chatcontact')),
            ],
            options={
                'unique_together': {('contact', 'attribute')},
            },
        ),
    ]
