# Generated by Django 5.2.4 on 2025-09-10 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_names', models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=250)),
                ('flow_data', models.JSONField(help_text='The entire JSON object from React Flow (nodes and edges).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
