# Generated by Django 5.2.4 on 2025-09-10 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFlowSessions',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flows')),
            ],
        ),
    ]
