# Generated by Django 5.2.4 on 2025-10-07 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flow', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlowForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta_flow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_category', models.CharField(default='UTILITY', max_length=50)),
                ('template_body', models.TextField()),
                ('template_button_text', models.CharField(default='Open Form', max_length=20)),
                ('screens_data', models.JSONField()),
                ('flow_status', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Flow Form',
                'verbose_name_plural': 'WhatsApp Flow Forms',
            },
        ),
        migrations.AddField(
            model_name='contactattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_values', to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='contactattributevalue',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='registration.chatcontact'),
        ),
        migrations.CreateModel(
            name='UserFlowSessions',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_waiting_for_location', models.BooleanField(default=False)),
                ('waiting_for_flow_completion', models.BooleanField(default=False)),
                ('flow_form_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flows')),
                ('latitude_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latitude_sessions', to='flow.attribute')),
                ('longitude_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longitude_sessions', to='flow.attribute')),
                ('waiting_for_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.attribute')),
                ('waiting_for_image_attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sessions', to='flow.attribute')),
            ],
            options={
                'verbose_name_plural': 'User Flow Sessions',
            },
        ),
        migrations.CreateModel(
            name='UserFlowSessionss',
            fields=[
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='registration.chatcontact')),
                ('current_node_id', models.CharField(help_text="The ID of the user's current node in the flow.", max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flow.flowss')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, help_text='The unique ID from Meta for this call', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(default='initiated', help_text='e.g., ringing, answered, ended, missed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when the call was ended or missed', null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='registration.chatcontact')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contactattributevalue',
            unique_together={('contact', 'attribute')},
        ),
    ]
