# Generated by Django 5.2.4 on 2025-09-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_flows_userflowsessions_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flows',
            name='template_name',
            field=models.CharField(help_text='The template that triggers this flow. Other templates can be used inside.', max_length=255),
        ),
    ]
