# Generated by Django 5.2.4 on 2025-09-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_flows_userflowsessions'),
    ]

    operations = [
        migrations.AddField(
            model_name='flows',
            name='name',
            field=models.CharField(default='Untitled Flow', max_length=255, unique=True),
        ),
    ]
