# Generated by Django 5.2.4 on 2025-09-10 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flows',
            old_name='template_names',
            new_name='template_name',
        ),
    ]
