# Generated by Django 5.2.4 on 2025-09-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0003_flows_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='flows',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the flow is currently active and can be triggered.'),
        ),
    ]
