# Generated by Django 5.2.4 on 2025-09-11 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0004_flows_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flows',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Flows'},
        ),
        migrations.AlterModelOptions(
            name='userflowsessions',
            options={'verbose_name_plural': 'User Flow Sessions'},
        ),
    ]
