# Generated by Django 5.2.4 on 2025-09-19 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0005_alter_flows_options_alter_userflowsessions_options'),
        ('registration', '0003_message_source_node_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_values', to='flow.attribute')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='registration.chatcontact')),
            ],
            options={
                'unique_together': {('contact', 'attribute')},
            },
        ),
    ]
