# Generated by Django 5.2.4 on 2025-09-20 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_attribute_contactattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflowsessions',
            name='is_waiting_for_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='latitude_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latitude_sessions', to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='longitude_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longitude_sessions', to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_image_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sessions', to='flow.attribute'),
        ),
    ]
