# Generated by Django 5.2.4 on 2025-09-19 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0006_attribute_contactattributevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flow.attribute'),
        ),
    ]
