# Generated by Django 5.2.4 on 2025-09-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_userflowsessions_is_waiting_for_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppFlowForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('meta_flow_id', models.CharField(blank=True, max_length=255, null=True)),
                ('template_category', models.CharField(default='UTILITY', max_length=50)),
                ('template_body', models.TextField()),
                ('template_button_text', models.CharField(default='Open Form', max_length=20)),
                ('screens_data', models.JSONField()),
                ('flow_status', models.CharField(blank=True, max_length=50, null=True)),
                ('template_name', models.CharField(blank=True, max_length=255, null=True)),
                ('template_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Flow Form',
                'verbose_name_plural': 'WhatsApp Flow Forms',
            },
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='flow_form_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_flow_completion',
            field=models.BooleanField(default=False),
        ),
    ]
