# Generated by Django 5.2.4 on 2025-09-19 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0007_userflowsessions_waiting_for_attribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_image_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_sessions', to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='waiting_for_location_data',
            field=models.JSONField(blank=True, help_text='Stores which attributes to save lat/lon to.', null=True),
        ),
    ]
