# Generated by Django 5.2.4 on 2025-09-25 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_whatsappflowform_userflowsessions_flow_form_id_and_more'),
        ('registration', '0004_whatsappform'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, help_text='The unique ID from Meta for this call', max_length=255, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('status', models.CharField(default='initiated', help_text='e.g., ringing, answered, ended, missed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ended_at', models.DateTimeField(blank=True, help_text='Timestamp when the call was ended or missed', null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='registration.chatcontact')),
            ],
        ),
    ]
