# Generated by Django 5.2.4 on 2025-09-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flow', '0008_userflowsessions_waiting_for_image_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflowsessions',
            name='waiting_for_location_data',
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='is_waiting_for_location',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='latitude_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latitude_sessions', to='flow.attribute'),
        ),
        migrations.AddField(
            model_name='userflowsessions',
            name='longitude_attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='longitude_sessions', to='flow.attribute'),
        ),
    ]
